### ISSUE TITLE
xargs on GNU does not ignore empty input from STDIN

### ISSUE THREAD

**Issue by Weltraumschaf** [barthel/maven-utils#3]
On some GNU environments (especially Git Bash on Windows 10) the `xargs` command which invokes the `sed` command passes empty input from the previous `grep` to sed. This results in an 'no input file' error.

Reproduce:

```bash
set-dependency-version.sh taco.se.deb 1.2.3
```

The fix for GNU systems is to add the option `-r` to `xargs` in `set-dependency-version-in-all-manifests.sh`:

```diff
@@ -85,7 +85,7 @@ _cmd="$(_build_find_cmd "${_find_filter}") "
_cmd+=" | xargs "
# 2. '_build_grep_cmd ...' - select file names containing the bundle version string
_cmd+="$(_build_grep_cmd "${_grep_filter}") "
_cmd+=" | xargs "
_cmd+=" | xargs -r"
# 3. '_build_sed_cmd ...'  - inline replace of version
_cmd+="$(_build_sed_cmd "${_sed_filter}") "
```

But on Unix systems like macOS there is no such option `-r`.

**Comment by barthel** [comment]
Many thanks for contribution.

I've fixed this issue for use with Linux (GNU) and macOS (BSD) ```xargs``` variants.
